server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://192.168.1.111:5432/formation?currentSchema=abdeljalil_schema
    driverClassName: org.postgresql.Driver
    username: xcom
    password: mb65DbP2HbpSY606
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  cloud:
    consul:
      enabled: false
      config:
        enabled: false
